services:

  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: collection
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql

    # Allows ensuring that database is ready before starting server.
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  deno:
    container_name: deno-react-server
    restart: always
    build:
      context: ./webapp
      dockerfile: docker/deno.dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./webapp:/app
    environment:
      ROLE: "server"

    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

  dbutil:
    container_name: dbutil
    restart: always
    build:
      context: dbutil
      dockerfile: dbutil.dockerfile
    ports:
      - target: 50051
        published: 50051
        protocol: tcp
        mode: host
    volumes:
      - ./dbutil/scripts:/scripts

    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
