// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: clz_xml_rpc/clz_xml.proto

package clzxmlserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClzXml_Parse_FullMethodName = "/clz_xml.ClzXml/Parse"
)

// ClzXmlClient is the client API for ClzXml service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClzXmlClient interface {
	Parse(ctx context.Context, in *File, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BookRecord], error)
}

type clzXmlClient struct {
	cc grpc.ClientConnInterface
}

func NewClzXmlClient(cc grpc.ClientConnInterface) ClzXmlClient {
	return &clzXmlClient{cc}
}

func (c *clzXmlClient) Parse(ctx context.Context, in *File, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BookRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClzXml_ServiceDesc.Streams[0], ClzXml_Parse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[File, BookRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClzXml_ParseClient = grpc.ServerStreamingClient[BookRecord]

// ClzXmlServer is the server API for ClzXml service.
// All implementations must embed UnimplementedClzXmlServer
// for forward compatibility.
type ClzXmlServer interface {
	Parse(*File, grpc.ServerStreamingServer[BookRecord]) error
	mustEmbedUnimplementedClzXmlServer()
}

// UnimplementedClzXmlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClzXmlServer struct{}

func (UnimplementedClzXmlServer) Parse(*File, grpc.ServerStreamingServer[BookRecord]) error {
	return status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedClzXmlServer) mustEmbedUnimplementedClzXmlServer() {}
func (UnimplementedClzXmlServer) testEmbeddedByValue()                {}

// UnsafeClzXmlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClzXmlServer will
// result in compilation errors.
type UnsafeClzXmlServer interface {
	mustEmbedUnimplementedClzXmlServer()
}

func RegisterClzXmlServer(s grpc.ServiceRegistrar, srv ClzXmlServer) {
	// If the following call pancis, it indicates UnimplementedClzXmlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClzXml_ServiceDesc, srv)
}

func _ClzXml_Parse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(File)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClzXmlServer).Parse(m, &grpc.GenericServerStream[File, BookRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClzXml_ParseServer = grpc.ServerStreamingServer[BookRecord]

// ClzXml_ServiceDesc is the grpc.ServiceDesc for ClzXml service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClzXml_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clz_xml.ClzXml",
	HandlerType: (*ClzXmlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Parse",
			Handler:       _ClzXml_Parse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clz_xml_rpc/clz_xml.proto",
}
