// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: clz_xml_rpc/clz_xml.proto

package clzxmlserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_clz_xml_rpc_clz_xml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_clz_xml_rpc_clz_xml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_clz_xml_rpc_clz_xml_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BookRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string          `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year      *int32          `protobuf:"varint,2,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Isbn      *string         `protobuf:"bytes,3,opt,name=isbn,proto3,oneof" json:"isbn,omitempty"`
	Publisher *string         `protobuf:"bytes,4,opt,name=publisher,proto3,oneof" json:"publisher,omitempty"`
	Authors   []*AuthorRecord `protobuf:"bytes,5,rep,name=authors,proto3" json:"authors,omitempty"`
}

func (x *BookRecord) Reset() {
	*x = BookRecord{}
	mi := &file_clz_xml_rpc_clz_xml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRecord) ProtoMessage() {}

func (x *BookRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clz_xml_rpc_clz_xml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRecord.ProtoReflect.Descriptor instead.
func (*BookRecord) Descriptor() ([]byte, []int) {
	return file_clz_xml_rpc_clz_xml_proto_rawDescGZIP(), []int{1}
}

func (x *BookRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookRecord) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *BookRecord) GetIsbn() string {
	if x != nil && x.Isbn != nil {
		return *x.Isbn
	}
	return ""
}

func (x *BookRecord) GetPublisher() string {
	if x != nil && x.Publisher != nil {
		return *x.Publisher
	}
	return ""
}

func (x *BookRecord) GetAuthors() []*AuthorRecord {
	if x != nil {
		return x.Authors
	}
	return nil
}

type AuthorRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *AuthorRecord) Reset() {
	*x = AuthorRecord{}
	mi := &file_clz_xml_rpc_clz_xml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorRecord) ProtoMessage() {}

func (x *AuthorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clz_xml_rpc_clz_xml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorRecord.ProtoReflect.Descriptor instead.
func (*AuthorRecord) Descriptor() ([]byte, []int) {
	return file_clz_xml_rpc_clz_xml_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorRecord) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AuthorRecord) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_clz_xml_rpc_clz_xml_proto protoreflect.FileDescriptor

var file_clz_xml_rpc_clz_xml_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6c, 0x7a, 0x5f, 0x78, 0x6d, 0x6c, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6c,
	0x7a, 0x5f, 0x78, 0x6d, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x7a,
	0x5f, 0x78, 0x6d, 0x6c, 0x22, 0x1a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x22, 0xc8, 0x01, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x88, 0x01, 0x01, 0x12, 0x17,
	0x0a, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04,
	0x69, 0x73, 0x62, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x07, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6c,
	0x7a, 0x5f, 0x78, 0x6d, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x79, 0x65, 0x61, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x73, 0x62, 0x6e, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x0c, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x39, 0x0a, 0x06, 0x43, 0x6c, 0x7a, 0x58, 0x6d, 0x6c, 0x12,
	0x2f, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x73, 0x65, 0x12, 0x0d, 0x2e, 0x63, 0x6c, 0x7a, 0x5f, 0x78,
	0x6d, 0x6c, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x13, 0x2e, 0x63, 0x6c, 0x7a, 0x5f, 0x78, 0x6d,
	0x6c, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x12, 0x5a, 0x10, 0x74, 0x75, 0x69, 0x2f, 0x63, 0x6c, 0x7a, 0x78, 0x6d, 0x6c, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clz_xml_rpc_clz_xml_proto_rawDescOnce sync.Once
	file_clz_xml_rpc_clz_xml_proto_rawDescData = file_clz_xml_rpc_clz_xml_proto_rawDesc
)

func file_clz_xml_rpc_clz_xml_proto_rawDescGZIP() []byte {
	file_clz_xml_rpc_clz_xml_proto_rawDescOnce.Do(func() {
		file_clz_xml_rpc_clz_xml_proto_rawDescData = protoimpl.X.CompressGZIP(file_clz_xml_rpc_clz_xml_proto_rawDescData)
	})
	return file_clz_xml_rpc_clz_xml_proto_rawDescData
}

var file_clz_xml_rpc_clz_xml_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clz_xml_rpc_clz_xml_proto_goTypes = []any{
	(*File)(nil),         // 0: clz_xml.File
	(*BookRecord)(nil),   // 1: clz_xml.BookRecord
	(*AuthorRecord)(nil), // 2: clz_xml.AuthorRecord
}
var file_clz_xml_rpc_clz_xml_proto_depIdxs = []int32{
	2, // 0: clz_xml.BookRecord.authors:type_name -> clz_xml.AuthorRecord
	0, // 1: clz_xml.ClzXml.Parse:input_type -> clz_xml.File
	1, // 2: clz_xml.ClzXml.Parse:output_type -> clz_xml.BookRecord
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clz_xml_rpc_clz_xml_proto_init() }
func file_clz_xml_rpc_clz_xml_proto_init() {
	if File_clz_xml_rpc_clz_xml_proto != nil {
		return
	}
	file_clz_xml_rpc_clz_xml_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clz_xml_rpc_clz_xml_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clz_xml_rpc_clz_xml_proto_goTypes,
		DependencyIndexes: file_clz_xml_rpc_clz_xml_proto_depIdxs,
		MessageInfos:      file_clz_xml_rpc_clz_xml_proto_msgTypes,
	}.Build()
	File_clz_xml_rpc_clz_xml_proto = out.File
	file_clz_xml_rpc_clz_xml_proto_rawDesc = nil
	file_clz_xml_rpc_clz_xml_proto_goTypes = nil
	file_clz_xml_rpc_clz_xml_proto_depIdxs = nil
}
