build:
	cargo build --package parser_grpc --bin parser_grpc

run:
	cargo run --package parser_grpc --bin parser_grpc

build_client:
	cargo build --package parser_grpc --bin parser_grpc_client

run_client:
	cargo run --package parser_grpc --bin parser_grpc_client
